### ISSUE TITLE
support manual enum value

### ISSUE THREAD

**Issue by zijianhuang** [Azhaguthasan/TypescriptCodeDom#1]
enum Color {Red = 1, Green = 2, Blue = 4};

currently the library ignores the value definition in my  C# codes, thus the TS output will have only enum Color {Red, Green, Blue};

I have fixed the issue in my private clone of TypescriptcodeDom in TypescriptMemberField.cs.

In the Expand function, replace with the following:
            if (isEnum)
            {
                if (_member.InitExpression == null)
                {
                    return $"{_member.Name},";
                }
                else
                {
                    var initializationExpression = _expressionFactory.GetExpression(_member.InitExpression, new System.CodeDom.Compiler.CodeGeneratorOptions()).Evaluate();
                    return initializationExpression == null ? $"{_member.Name}," : $"{_member.Name}={initializationExpression},";
                }
            } 

Hopefully the official release will include this fix.

**Comment by Azhaguthasan** [comment]
Please push your changes!

**Comment by zijianhuang** [comment]
done
