### ISSUE TITLE
indented output

### ISSUE THREAD

**Issue by zijianhuang** [Azhaguthasan/TypescriptCodeDom#2]
when calling 
            var provider = new TypescriptCodeProvider();
            //   var provider = CodeDomProvider.CreateProvider("CSharp");
            CodeGeneratorOptions options = new CodeGeneratorOptions()
            {
                BracingStyle = "JS", //or C
                IndentString="    ",
            };
            using (StreamWriter writer = new StreamWriter(fileName))
            {  
                provider.GenerateCodeFromCompileUnit(targetUnit, writer, options);
            }

the output does not have indent. Apparently this is not yet implemented. The output:

module DemoWebApi.DemoData.Client{
export interface Constants{

}

export enum AddressType{
Postal=0,
Residential=1,
}

export enum MyEnumType{
First=1,
Two=2,
}

export interface Address{
street1: string;
street2: string;
city: string;
state: string;
postalCode: string;
country: string;
type: DemoWebApi.DemoData.Client.AddressType;
location: DemoWebApi.DemoData.Another.Client.MyPoint;
}

not critical. but a nice looking feature to have.

**Comment by zijianhuang** [comment]
Basically done. So now good enough for data type declarations:

module DemoWebApi.DemoData.Client{
    export enum AddressType{
        Postal,
        Residential,
    }

```
export enum Days{
    Sat=1,
    Sun=2,
    Mon=3,
    Tue=4,
    Wed=5,
    Thu=6,
    Fri=7,
}

export interface Address{
    street1: string;
    street2: string;
    city: string;
    state: string;
    postalCode: string;
    country: string;
    type: DemoWebApi.DemoData.Client.AddressType;
    location: DemoWebApi.DemoData.Another.Client.MyPoint;
}

export interface Entity{
    id: number;
    name: string;
    addresses: Array<DemoWebApi.DemoData.Client.Address>;
}

export interface Person extends DemoWebApi.DemoData.Client.Entity{
    surname: string;
    givenName: string;
    birthDate: void;
    id: number;
    name: string;
    addresses: Array<DemoWebApi.DemoData.Client.Address>;
}

export interface Company extends DemoWebApi.DemoData.Client.Entity{
    businessNumber: string;
    businessNumberType: string;
    id: number;
    name: string;
    addresses: Array<DemoWebApi.DemoData.Client.Address>;
}
```

}

module DemoWebApi.DemoData.Another.Client{
    export interface MyPoint{
        x: number;
        y: number;
    }
}

However, for complex method codes, the indented style is not perfect. And current design with DI framework Unity could be a problem blocking the effectiveness of refactoring. So it will be good to remove Unity from the whole design before further works.

**Comment by Azhaguthasan** [comment]
The changes are good!!!

Regarding the DI, I doubt that it will limit the refactoring. Currently, they way we pass the options for indentation should be modified. Irrespective of that, removing the DI should not be a problem, as we have other factories in place that enforce some loose coupling. But that it is not critical though. 

Also, a question. Where are you using this Code Dom? I used it for getting the typescripts from WSDL definition which is here: https://github.com/Azhaguthasan/WSDLToTypescriptProxyGenerator.

**Comment by zijianhuang** [comment]
Hi Azhaguthasan

You might have heard of TypeLite which generates TS data models through
reading POCO classes in an assembly. While TypeLite is good, however, it
won't fit in my usual development model which use DataContractAttribute to
declare the intention of exposing partial members of some types to the
world, and such model is good for POCO classes that have some EF code first
specific members which are not good to be exposed.

So, mine is to use something similar to TypeLite, but expose POCO classes
decorated by DataContractAttriubte. So, in some regards, similar to yours.
Yours is somehow more universal and cross platforms, while mine is only for
.NET assembly, and the TS codes is for ASP.NET Web API, not WCF.

I had actually finished the development, but not yet published in
http://webapiclientgen.codeplex.com/ as product, though you may find it in
source codes published.

When fixing some minor issues in #1 and #2, I had found the presence of
Unity had introduced some problems:
- The TS CodeDom is a small project, not worth of the overhead of a heavy
  DI framework like Unity.
- To make the CodeDom library popular, the dependency on a DI framework
  make it look too fat. In fact, the JScriptCodeProvider in .NET Framework
  has no dependency on any DI framework, and had well existed in .NET 1.1
  before Unity was developed.
- The relationships of classes used in CodeDom and TypeScript are well
  defined and stable, and the loose coupling introduced by DI framework as
  well as interfaces hide the relationships between classes, making the codes
  hard to read and refactoring, and over too long.

As you could read from webapiclientgen, you and I had started similar
attempts almost at the same time, though with different scopes. I see that
wsdl2tsproxygen has a potential of becoming something similar to
svcutil.exe which could read both wsdl and assembly.

On 18 October 2015 at 15:09, Azhaguthasan notifications@github.com wrote:

> The changes are good!!!
> 
> Regarding the DI, I doubt that it will limit the refactoring. Currently,
> they way we pass the options for indentation should be modified.
> Irrespective of that, removing the DI should not be a problem, as we have
> other factories in place that enforce some loose coupling. But that it is
> not critical though.
> 
> Also, a question. Where are you using this Code Dom? I used it for getting
> the typescripts from WSDL definition which is here:
> https://github.com/Azhaguthasan/WSDLToTypescriptProxyGenerator.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Azhaguthasan/TypescriptCodeDom/issues/2#issuecomment-148978676
> .

## 

## 

Regards

Zijian
