### ISSUE TITLE
Do not automatically camelcase field / property names

### ISSUE THREAD

**Issue by spelltwister** [Azhaguthasan/TypescriptCodeDom#3]
Camel casing of the property names should be done when the code compile unit is generated and not in the typescript generator.  Please make this an option that can be disabled (or, I will likely submit a pull request for that).  I am working on some other components for the client generator including the code compile unit generator that I'll upload to demonstrate what this looks like.

It seems more appropriate to look at things like the JsonPropertyAttribute.Name property or DataMemberAttribute.Name or whatever to see if there is an explicit transformation and set the exact desired name (possibly Pascal cased) for the property.

Great job on this generator!  Saved me tons of time and effort.  I'm super glad I ran into this project!

**Comment by zijianhuang** [comment]
there's a new implementation of TypeScript CodeDOM at https://webapiclientgen.codeplex.com/wikipage?title=camelCasing%20or%20PascalCasing%3f  supporting optional camelCase.

**Comment by spelltwister** [comment]
The linked codebase is a waaay different implementation.  This one is much more complete and already very loosely coupled with inject-able dependencies.  I have investigated both and uploaded some sample projects that are a refactoring of the link you provided.  https://github.com/spelltwister/ClientGenerator
